# Generated by Django 2.2 on 2022-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
